language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "gAFUJgHLKHsoC0Y8/QC6i+PdyvJE/OSGfEc1JRhPUAk7l1sN7mC7070bSV03Gpg7ldCIBUXKa3Md3bORmdvYgSH0PfGxc0kRcqUPM1mJJFw5mOtuxNQ0FnE5BQ7FMJWzPHQnt6JIAeusMFpLWa1pddVq4dbJ2i4V0wrskSavWingAuWQKXv7jPYWExoeKtpxEx3QmueJUcJR8yDAtun65K8SbhEtxJTnoIO2FfYnK7aNQkhK7XvWDPcNC8CM/pekWgRiLn+1uS68q63zzcCnaUDrdaCBrNzn8ud7l/d85DNhxZb3e0BLllmgXbWTtNDmeCtpOLSQjkdYZu97ykrToLdOMlRSqGLY9HlUOTvynLbFUO2eKq6Hl4JHJfQ+b19pCCZBRMiz5YFbGwbXuJfN1daITl5TQkUfkqgrkq4bf9KSBRlfS6R7OVyFYmG7YRh+PwW+DFiWbS1giN9GRzfYM5266xCYIc5FbgbG3Y/u3zdJ9FCvv7WqM4agkEFnZW+HPF07sxsz+iWqLlmUtKrMrp1NYUA9Nk9f0ocN2cBZgiUfmpzfwqEkUbsaBlfFGpAfO2f/nzeZ8EjxbwmQOG3DEhbHwNMzf6HwFq4KX+mlwigild2v0EfGibkQzmnWVrHiSz77oIkO8XVPm8eD/YqMczYaPfJ4TtI+DBXh1b9sYcI="
