language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Gbx8jbRXgkzps0e370lbVbSa0OGFy1nLPerYh+2AWmf4ahsh6q00RIyKEX6WM00Fum46uZGOQ8vYcEBEoQkYvUXWuk+ATG1W8a2ylSE0oGALHnYANv8SLAb+jar5NOvpOeQ8qhYXkeiLrHHsHRV28ppEDwnJZhrF2fi70nwDbNVTMP9oPJTvDSG2xo9joS3HtR8pl6M+zd+6ivdEUndE/uWc8KKdORZDFiH2Gk7PxHYWKMlP9rC+ImsGFRmtZiYtFDUbqiPfYvUBN0VaMWmZ5F0hd4XayijwjwNHN+54waWShZSyQ84RAfUg/bZO52tOzYGgEyAI7o6J2Y9JVYbfPGuKuFWlPZEjr0YABHeXRIjot2lI8gptVzG5KMHnGzDbymVgABS85rCblf96c9yHpoqL9Wiftua+irr90gJdJ140Dd4p2rVJzmuZ0FQJIehrKXaK+XDFsaxksI6hb65Lca+VZdHzIdZ8LXo0PHZRfRvPnJNe7C8jX8MplTnee0pJV6g23wlJBsCONuD3Ub3iNGgJt7Z84kLyfxL5nFKslBf2cyhA1Z2kjLiWmlQnT202h0xcNdbIsh9nNW2zUbcqD1HM/lyYNwmu2dVcNNJdK7LR+hq5hFlI7IbNNa/TWF0AgXUBMy0tIWFAHbcFWeZrcmOOnQ0cMHfoNVW2o8Y6o28="
env:
  secure: "A7cLhPbKJUg3v0LwkHEwcOXH/P+VqxXWFsz7abrjvtwAb4bVL5lq+ElTLwlOjU7g+V7XXvt3+pMji1GQhRYZ+0aH+uZ46VT//BkJZ4EuPbnsZxJDxLFyB5GwK8HmMb/pmplMgVWLlGju+t9ko8uJWrNQavxsC2wuXZakSeYpERrKlr6Ggyyr0Z8EES9IEHbXK/e/f/Hmsnh1PxHrUd5p8DQ9pWbCJnE8f8pCMy67WmjV8kachjZOTKDDd5GaRpiJt/0GHkBZ4nUBJCJsqotXxrEL4qnlbLxiSFZ3fWAF28mR0wGZ+5tmh2WswVF4whuw2ZfIw4sR5FTlOIWEExBScPjkxLeJGhAHtm5ojdld3fx+VKVukZOyBh6nirN+KNZ9Oo3rHf+cY85qntdIkpKiDDYeXiVcogsQB2VLNsCByrcjoRejBSKllErlziaFOh1TFzMnwcZkxQKS65u6FomfAzfa3ErKWDiu+M1h+fnqN6q22qGNheWUaOTlR9K2e3eBa1d9AJ8grKi0bwfCGl0r1qbKC3Mrt392sHtVGK8IK5YxtUFuM0Sa+jZA9xNs2P6/Ztf9iwmnvZMrRwF+wJo16qYCFC+2nCHeUbPgQfrqHnuboOvM71PyBazS8qDQ8Na8CWUQjLTCw8bFVsCyELIsbrcEqv0w4HHiobVr/yJPHY0="
