language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js


env:
  secure: "n/Yxt58L6vLPWWjmWMEw2sC5ANjzBUW23FQSvyMNg0L9NJMqvk7D64KeDIs5o8BEWnv8H4V3rDR85ZgI9418s3r0RX0lhOhMOcSkQer5oXEoeEdlrytQ3x1nHZoUGeq2phxN+8ZFL+YpcgumQvWbOmMAKQsGmhstfnOWlv93hu+nDL7f9gSrjpXl2K//Pg81mn+NcEAJG/TPFdxpB24M6Jqa+OGjMuYwt4ObDtWPbcHjxjkHwyVRd8XH0zXEAzqfLxYDQ2N9Mt6kIAG2R13q5rk2wxmQdWFs545kPCoBlW6vkgEIBXIsIL9Efq0N4tCmHGvAxFXDq1LgdOVJ/FcCITOqmOYMrrNOiBu5VVEFri7RF/827fiLnU0z1+1+nlO7ZRq8lPrNXZXNkn9fkdZWTLHUQmVzePXiI2MOSOcqvivuhlInTdYheBvPRVBGgEg475I9W95PHEKtWpvkXapsI+i+x8ZIZYbagnsAwhVIv792N9XUFCxbgXfVgFeI8RuEegXkMeXDDpG6eml3ziy+OZhRLt7hzR4Rn8TKm15HYMQBtmlhhOOip42Lnvxs8xe0zwgF7KqCjc5vEmHgrwuKdRQ9PiIKWdJzfO7jeQb+7329zMos6BFdLpC/lJbNeBEaQBUulD2SE6y3EX0OktZ6aq/D8TVIoF5LaMQ2g+UyOVo="
